services:
  - type: web
    name: chinook-album-management
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2
    envVars:
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-database-user
      - key: DB_PASS
        value: your-database-password
      - key: DB_NAME
        value: chinook 